{{- if .Values.services.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "overleaf.fullname" . }}-web
  labels:
    {{- include "overleaf.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "overleaf.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
{{- end }}
