{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "overleaf.fullname" . }}-data
  labels:
    {{- include "overleaf.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "overleaf.fullname" . }}-templates
  labels:
    {{- include "overleaf.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.templates.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "overleaf.fullname" . }}-history
  labels:
    {{- include "overleaf.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.history.size }}
{{- end }}
