apiVersion: v1
kind: Service
metadata:
  name: overleaf-clsi
  namespace: overleaf
  labels:
    app.kubernetes.io/component: clsi
spec:
  type: ClusterIP
  ports:
    - port: 3013
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: overleaf
    app.kubernetes.io/component: clsi
